name: ci

concurrency:
  cancel-in-progress: ${{ ! startsWith(github.ref, 'refs/tags/') }}
  group: ci-${{ github.ref_name }}-${{ github.event_name }}

on:
  push:
    branches:
      - main

jobs:
  build-main:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-docker.yml
    with:
      context: .
      image-name: ghcr.io/${{ github.repository }}
      image-extra-tags: |
        ghcr.io/${{ github.repository }}:${{ github.run_id }}
        ghcr.io/${{ github.repository }}:latest
      platforms: linux/amd64,linux/arm64
      push: ${{ github.event_name == 'push' }}
      scout-cves: false
      scout-compare: false
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
